/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginPatientIndexRouteImport } from './routes/login/patient/index'
import { Route as LoginDoctorIndexRouteImport } from './routes/login/doctor/index'
import { Route as RegisterPatientRegisterRouteImport } from './routes/register/patient/register'
import { Route as RegisterDoctorRegisterRouteImport } from './routes/register/doctor/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPatientIndexRoute = LoginPatientIndexRouteImport.update({
  id: '/login/patient/',
  path: '/login/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDoctorIndexRoute = LoginDoctorIndexRouteImport.update({
  id: '/login/doctor/',
  path: '/login/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPatientRegisterRoute = RegisterPatientRegisterRouteImport.update({
  id: '/register/patient/register',
  path: '/register/patient/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterDoctorRegisterRoute = RegisterDoctorRegisterRouteImport.update({
  id: '/register/doctor/register',
  path: '/register/doctor/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/register/doctor/register': typeof RegisterDoctorRegisterRoute
  '/register/patient/register': typeof RegisterPatientRegisterRoute
  '/login/doctor/': typeof LoginDoctorIndexRoute
  '/login/patient/': typeof LoginPatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/register/doctor/register': typeof RegisterDoctorRegisterRoute
  '/register/patient/register': typeof RegisterPatientRegisterRoute
  '/login/doctor': typeof LoginDoctorIndexRoute
  '/login/patient': typeof LoginPatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/register/doctor/register': typeof RegisterDoctorRegisterRoute
  '/register/patient/register': typeof RegisterPatientRegisterRoute
  '/login/doctor/': typeof LoginDoctorIndexRoute
  '/login/patient/': typeof LoginPatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/register/'
    | '/register/doctor/register'
    | '/register/patient/register'
    | '/login/doctor/'
    | '/login/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/register/doctor/register'
    | '/register/patient/register'
    | '/login/doctor'
    | '/login/patient'
  id:
    | '__root__'
    | '/'
    | '/login/'
    | '/register/'
    | '/register/doctor/register'
    | '/register/patient/register'
    | '/login/doctor/'
    | '/login/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  RegisterDoctorRegisterRoute: typeof RegisterDoctorRegisterRoute
  RegisterPatientRegisterRoute: typeof RegisterPatientRegisterRoute
  LoginDoctorIndexRoute: typeof LoginDoctorIndexRoute
  LoginPatientIndexRoute: typeof LoginPatientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/patient/': {
      id: '/login/patient/'
      path: '/login/patient'
      fullPath: '/login/patient/'
      preLoaderRoute: typeof LoginPatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/doctor/': {
      id: '/login/doctor/'
      path: '/login/doctor'
      fullPath: '/login/doctor/'
      preLoaderRoute: typeof LoginDoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/patient/register': {
      id: '/register/patient/register'
      path: '/register/patient/register'
      fullPath: '/register/patient/register'
      preLoaderRoute: typeof RegisterPatientRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/doctor/register': {
      id: '/register/doctor/register'
      path: '/register/doctor/register'
      fullPath: '/register/doctor/register'
      preLoaderRoute: typeof RegisterDoctorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  RegisterDoctorRegisterRoute: RegisterDoctorRegisterRoute,
  RegisterPatientRegisterRoute: RegisterPatientRegisterRoute,
  LoginDoctorIndexRoute: LoginDoctorIndexRoute,
  LoginPatientIndexRoute: LoginPatientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
